name: Netlify Plugin Sitemap Test

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [8.12.0, 15.x]
        exclude:
          - os: macOS-latest
            node-version: 8.12.0
          - os: windows-latest
            node-version: 8.12.0
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run format:ci
        if: "${{ matrix.node-version == '15.x' }}"
      - name: Tests
        run: npm test
